USE [master]
GO

/****** Object:  Database [AkijBashirGroup]    Script Date: 9/14/2023 1:35:55 AM ******/
CREATE DATABASE [AkijBashirGroup]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AkijBashirGroup', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AkijBashirGroup.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AkijBashirGroup_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AkijBashirGroup_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AkijBashirGroup].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AkijBashirGroup] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET ARITHABORT OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AkijBashirGroup] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AkijBashirGroup] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AkijBashirGroup] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AkijBashirGroup] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET RECOVERY FULL 
GO

ALTER DATABASE [AkijBashirGroup] SET  MULTI_USER 
GO

ALTER DATABASE [AkijBashirGroup] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AkijBashirGroup] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AkijBashirGroup] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AkijBashirGroup] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AkijBashirGroup] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AkijBashirGroup] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AkijBashirGroup] SET  READ_WRITE 
GO

